title: Mikun Pham, Front-End Developer
name: Mikun Pham
description: My name is Pham Quan, Front-End Developer and UI Designer. Nice to meet you.
baseurl: ""
twitter_username: phammikun
github_username: mikunpham
url: "https://mikunpham.github.io"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty

exclude:
  - .gitignore
  - node_modules
  - package.json
  - README.md
  - CNAME